import { defineConfig, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno({ dark: 'class' }),
    presetIcons({
      scale: 1.2,
      warn: true,
      extraProperties: { display: 'inline-block', 'vertical-align': '-0.125em' },
    }),
  ],
  theme: {
    colors: {
      brand: {
        50: 'var(--bx-brand-50)',
        100: 'var(--bx-brand-100)',
        200: 'var(--bx-brand-200)',
        300: 'var(--bx-brand-300)',
        400: 'var(--bx-brand-400)',
        500: 'var(--bx-brand-500)',
        600: 'var(--bx-brand-600)',
        700: 'var(--bx-brand-700)',
        800: 'var(--bx-brand-800)',
        900: 'var(--bx-brand-900)',
        soft: 'var(--bx-brand-soft)',
        softHover: 'var(--bx-brand-soft-hover)',
      },
      bg: 'var(--bx-bg)',
      surface: 'var(--bx-surface)',
      surfaceHover: 'var(--bx-surface-hover)',
      surfaceAlt: 'var(--bx-surface-alt)',
      border: 'var(--bx-border)',
      borderStrong: 'var(--bx-border-strong)',
      text: { 1: 'var(--bx-text-1)', 2: 'var(--bx-text-2)', 3: 'var(--bx-text-3)' },
      success: 'var(--bx-success)',
      successSoft: 'var(--bx-success-soft)',
      warning: 'var(--bx-warning)',
      warningSoft: 'var(--bx-warning-soft)',
      error: 'var(--bx-error)',
      errorSoft: 'var(--bx-error-soft)',
      info: 'var(--bx-info)',
      infoSoft: 'var(--bx-info-soft)',
    },
    borderRadius: { sm: '4px', md: '8px', lg: '12px', xl: '16px' },
    boxShadow: { sm: 'var(--bx-shadow-sm)', md: 'var(--bx-shadow-md)', lg: 'var(--bx-shadow-lg)' },
  },
  shortcuts: [
    ['page', 'mx-auto w-full max-w-6xl px-6 py-6 space-y-6'],
    ['page-header', 'flex items-center justify-between gap-4 flex-wrap'],
    ['section-title', 'text-lg font-semibold text-text-1 flex items-center gap-2'],
    ['card', 'bg-surface border border-border rounded-md shadow-sm'],
    ['card-pad', 'p-5'],
    ['card-hover', 'transition-[box-shadow,border-color] duration-150 ease-in-out hover:shadow-md hover:border-brand-300 cursor-pointer'],
    ['btn-primary', 'inline-flex items-center gap-2 h-9 px-4 rounded-md bg-brand-500 text-white text-sm font-medium transition-colors duration-150 hover:bg-brand-400 active:bg-brand-600 disabled:opacity-50 disabled:cursor-not-allowed'],
    ['btn-ghost', 'inline-flex items-center gap-2 h-9 px-4 rounded-md text-text-2 text-sm font-medium transition-colors duration-150 hover:bg-surface-hover hover:text-text-1'],
    ['btn-danger', 'inline-flex items-center gap-2 h-9 px-4 rounded-md text-error text-sm font-medium border border-border transition-colors duration-150 hover:border-error hover:bg-error-soft'],
    ['chip', 'inline-flex items-center gap-1 px-2 py-0.5 rounded-sm text-xs bg-surface-alt border border-border text-text-2'],
    ['code-text', 'font-mono text-13px'],
    ['link', 'text-brand-500 hover:text-brand-400 hover:underline transition-colors duration-150 cursor-pointer'],
    ['text-13px', 'font-size:13px'],
    ['stat-value', 'text-2xl font-semibold font-mono text-text-1'],
    ['stat-label', 'text-sm text-text-3'],
    ['skeleton', 'animate-pulse bg-surface-hover rounded-md'],
    ['empty-wrap', 'flex flex-col items-center justify-center gap-3 py-16 text-center'],
    ['sidebar-item', 'flex items-center gap-2.5 px-3 h-9 rounded-md text-text-2 text-sm transition-colors duration-150 hover:bg-surface-hover hover:text-text-1 cursor-pointer'],
    ['sidebar-item-active', 'sidebar-item bg-brand-soft text-brand-600 hover:text-brand-600 hover:bg-brand-soft-hover font-medium'],
    ['sidebar-icon', 'text-16px shrink-0'],
    ['log-line', 'font-mono text-13px leading-6 break-all'],
    ['console-wrap', 'bg-surface-alt border border-border rounded-md p-4 overflow-auto font-mono text-13px leading-6'],
    ['focus-ring', 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 focus-visible:ring-offset-2 focus-visible:ring-offset-bg'],
  ],
})
